# Generated by Django 3.1 on 2020-08-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('stock_amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_details', models.CharField(max_length=200, null=True)),
                ('user_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('order_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order')),
            ],
        ),
    ]
