# Generated by Django 3.1 on 2020-09-28 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_rewards',
            name='rewards',
        ),
        migrations.AddField(
            model_name='customer_rewards',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='api.reward'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.restaurant'),
        ),
        migrations.AlterField(
            model_name='booking_order',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.booking'),
        ),
        migrations.AlterField(
            model_name='booking_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.order'),
        ),
        migrations.AlterField(
            model_name='customer_rewards',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to='api.meal'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='api.menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.meal'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant', to='api.restaurant'),
        ),
    ]
