# Generated by Django 3.1 on 2020-08-30 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_customer_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('rewards_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('points_percent', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='access',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Customer_Rewards',
            fields=[
                ('customer_rewardsID', models.IntegerField(primary_key=True, serialize=False)),
                ('rewards_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rewards')),
                ('user_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
    ]
