# Generated by Django 3.1 on 2020-10-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menu_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
    ]
