# Generated by Django 3.1 on 2020-10-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201013_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_rewards',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='customer_rewards',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='api.menu', unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.booking'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tax_file_number',
            field=models.CharField(max_length=9),
        ),
        migrations.DeleteModel(
            name='Booking_Order',
        ),
        migrations.DeleteModel(
            name='Customer_Rewards',
        ),
        migrations.DeleteModel(
            name='Menu_Item',
        ),
    ]
