# Generated by Django 3.1 on 2020-10-17 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_menu_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='reward',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 10, 17)),
        ),
    ]
