# Generated by Django 3.1 on 2020-09-29 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200929_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='code',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 9, 29)),
        ),
        migrations.AddField(
            model_name='reward',
            name='is_valid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='valid_until',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='points_percent',
            field=models.IntegerField(null=True),
        ),
    ]
