# Generated by Django 3.1 on 2020-10-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reward',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
