# Generated by Django 3.1 on 2020-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200929_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
