# Generated by Django 3.1 on 2020-10-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_lunch',
            field=models.BooleanField(default=False),
        ),
    ]
