# Generated by Django 3.1 on 2020-08-30 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200830_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Item',
            fields=[
                ('menu_ItemID', models.IntegerField(primary_key=True, serialize=False)),
                ('item_1', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('ingredient_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('item_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.item')),
            ],
        ),
    ]
