# Generated by Django 3.1 on 2020-10-16 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201013_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 10, 16)),
        ),
    ]
