# Generated by Django 3.1 on 2020-10-15 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201013_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='api.menu'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 10, 15)),
        ),
    ]
