# Generated by Django 3.1 on 2020-10-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
