# Generated by Django 3.1 on 2020-10-18 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='restaurant_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 10, 18)),
        ),
    ]
