# Generated by Django 3.1 on 2020-10-15 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201015_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.menu'),
        ),
    ]
