# Generated by Django 3.1 on 2020-10-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201015_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
