# Generated by Django 3.1 on 2020-10-16 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201015_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='cost',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='reward',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 10, 16)),
        ),
    ]
